version: "3"
services:
  calculator:
    image: prasantk/calculator:${TAG}
    # ports:
    #   - 8080
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=${URL}
      - VIRTUAL_PORT=8080
  redis:
    image: redis:4-alpine
networks:
  default:
    external:
      name: jenkins_default